name: 'retail_intelligence'
version: '1.0.0'
config-version: 2

profile: 'retail_warehouse'

model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_intelligence:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table